name: Daily Automated Actions
on:
  schedule:
    - cron: '1 20 * * *'

jobs:
  daily-run:
    name: 'Runs daily at midnight UTC'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Setup Python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Proccess accounts
        run: |
          python main.py -a "${{ secrets.auth_string_first }}" -e "${{ secrets.email_username }}" -p "${{ secrets.email_password }}" -r "${{ secrets.email_recipient }}"
          python main.py -a "${{ secrets.auth_string_second }}" -e "${{ secrets.email_username }}" -p "${{ secrets.email_password }}" -r "${{ secrets.email_recipient }}"
          python main.py -a "${{ secrets.auth_string_third }}" -e "${{ secrets.email_username }}" -p "${{ secrets.email_password }}" -r "${{ secrets.email_recipient }}"
          python main.py -a "${{ secrets.auth_string_fourth }}" -e "${{ secrets.email_username }}" -p "${{ secrets.email_password }}" -r "${{ secrets.email_recipient }}"
          python main.py -a "${{ secrets.auth_string_fifth }}" -e "${{ secrets.email_username }}" -p "${{ secrets.email_password }}" -r "${{ secrets.email_recipient }}"
